version: '3.11'

services:
  db:
    container_name: product-app-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/postgresql/data

  server:
    container_name: chat_server
    build: .
    environment:
      DATABASE_URL: "postgresql+pg8000://root:root@db:5432/product_db"
      DEBUG: '1'
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    ports:
      - "8008:8000"
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: always